---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      exclude_paths:
      - "spec/"
      - "db/"
      - "**/vendor/"
  fixme:
    enabled: false
  rubocop:
    enabled: false
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
exclude_paths:
- test/*
