---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  flog:
    enabled: true
    config:
      all: false
      threshold: 0.6
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
exclude_paths:
- spec/
- db/
- "**/vendor/"
