version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      DATABASE_URL: 'postgres://postgres:@db:5432'
    volumes:
      - .:/hacken-in
    ports:
      - "3000:3000"
    depends_on:
      - db
