version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    image: moonglum/hacken-in:latest
    environment:
      RAILS_ENV: "development"
      DATABASE_URL: 'postgres://postgres:@db:5432'
    env_file: .env
    volumes:
      - ".:/app"
      - "./vendor/gems:/gems"
    user: "${USERID:-1000}"
    ports:
      - "3000:3000"
    depends_on:
      - db
