version: '3'
services:
  db:
    image: postgres
  web:
    image: hackenin/hacken-in:latest
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    environment:
      RAILS_ENV: "development"
      DATABASE_URL: 'postgres://postgres:@db:5432'
      BUNDLE_APP_CONFIG: /gems
      GEM_HOME: "/gems"
    env_file: .env
    volumes:
      - ".:/app"
      - "./vendor/gems:/gems"
    user: "${USER_MAPPING:-1000:1000}"
    ports:
      - "3000:3000"
    depends_on:
      - db
