#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
require 'open3'
require 'resolv'

class NullThread
  def self.value
    new
  end
  def success?
    true
  end
end

class Step
  DEFAULT_SOLUTION = <<-EOT
    Please copy the complete output and open a ticket
    at https://github.com/hacken-in/website/issues/new\n
  EOT

  attr_reader :block, :title

  def initialize(title)
    @title = title
    @solution = DEFAULT_SOLUTION
  end

  def unindent_heredoc(string)
    string.gsub(/^[ \t]{4}/, '')
  end

  def solution(solution = nil)
    if solution
      @solution = unindent_heredoc(solution)
    else
      @solution
    end
  end

  def run(command = nil, &block)
    if command
      @block = lambda { Open3.popen3(command) }
    else
      @block = block
    end
    execute
  end

  def execute
    _, stdout, stderr, thread = block.call
    thread ||= NullThread # YOLO
    raise [stdout.read, stderr.read].join("\n") unless thread.value.success?
    puts "\e[32m☑ #{title} looks healthy.\e[0m"
  rescue => e
    puts "\e[31m☒ #{title} check failed. :-(.\e[0m"
    puts "#{solution}\n"
    puts "Technical details:"
    raise e
  end
end

def step(title, &block)
  step = Step.new(title)
  step.instance_eval(&block)
end

step "Bundler Installation" do
  solution <<-EOL
    Please Install Bundler.
    -----------------------

    Run

      $ gem install bundler

    Then run script/bootstrap again.
  EOL
  run "bundle --version"
end

step "Bundler Run" do
  solution <<-EOL
    Bundle install failed.
    ----------------------

    We couldn't install Gems to the directory vendor/. Check your internet
    connectivity and see if https://status.rubygems.org is online.

    Then try again.
  EOL

  run "cd vagrant; bundle install --path=vendor"
end


step "Puppet Module installation" do

  solution <<-EOL
    Puppet module installation failed.
    ----------------------

    We couldn't install Puppet Modules to the puppet/modules
    directory. Check your internet connectivity and see if
    https://forge.puppetlabs.com is online.

    Then try again.
  EOL

  run "cd vagrant; bundle exec librarian-puppet install --path=puppet/modules"
end

step "Vagrant installation" do
  solution <<-EOL
    Sorry, you don't have Vagrant installed.
    ----------------------------------------

    Download the latest Version of Vagrant from https://www.vagrantup.com
    and try again.
  EOL
  run "vagrant --version"
end

step "Vagrant run." do
  puts "  You will be asked for your System Password, so Vagrant can mount"
  puts "  Files into the virtual machine. This will only happen once."
  run "vagrant up"
end

step "Try to resolve hacken.local" do
  solution <<-EOL
    Sorry, I couldn't resolve hacken.local
    --------------------------------------

    If you don't have a local resolver, please add the following line
    to your /etc/hosts file

      192.168.33.100 hacken.local www.hacken.local

    and try again.
  EOL
  run { Resolv.getaddress("hacken.local") }
end

puts "\nAll green, you are ready to go! Good work."
puts "Just open http://hacken.local in your browser."
