#!/usr/bin/env ruby

require 'tmpdir'
require 'logger'
logger = Logger.new(STDOUT)

Dir.mktmpdir do |dir|
  logger.info "Halting master application"
  system "svc -d ~/service/hacken-in-master"

  logger.info "Dumping hacken-in-production"
  system "pg_dump -O hacken-in-production > #{dir}/production.sql"

  system "dropdb hacken-in-master"
  system "createdb -O hacken-in-master hacken-in-master"

  logger.info "Restoring production DB to hacken-in-master"
  system "psql -U hacken-in-master -d hacken-in-master < #{dir}/production.sql"

  logger.info "Syncing uploads from production to master"
  system "rsync -a --delete /var/www/virtual/hacken/hacken.in/uploads/ /var/www/virtual/hacken/master.hacken.in/uploads/"

  logger.info "Starting master application"
  system "svc -u ~/service/hacken-in-master"
end
