#!/usr/bin/env ruby

DEPLOY_KEY="config/travis/travis-deploy-key"

system "openssl aes-256-cbc -K $encrypted_ece5f7dc116b_key -iv $encrypted_ece5f7dc116b_iv -in #{DEPLOY_KEY}.enc -out #{DEPLOY_KEY} -d"
File.chmod(0600, DEPLOY_KEY)
system("ssh-add #{DEPLOY_KEY}")

case ENV["TRAVIS_BRANCH"]
when "back-to-uberspace" then system "bundle exec cap master deploy"
when "master" then puts "NOT YET!"
end

